version: '3.4'
services:
  examples:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION:-8}
        - COMPOSER_VERSION=${COMPOSER_VERSION:-2}
    tty: true
    volumes:
      - vendor:/srv/vendor
      - .:/srv
    command: composer check
volumes:
  vendor:
